### PR TITLE
Do I have superpowers?

### PR DESCRIPTION
**Pull request by jennybc**
I have Unchecked the "Allow edits from maintainers" box.

After you `pr_fetch()`, I expect you won't be able to `pr_push()` into it.

But I think you can toggle this like so:

``` r
pr <- gh::gh(
  "PATCH /repos/:owner/:repo/pulls/:number",
  owner = "jtr13",
  repo = "usethis-demos",
  number = 000, # you need to fill this in
  maintainer_can_modify = TRUE,
  .token = Sys.getenv("GITHUB_PAT")
)
```

And then `pr_push()` will succeed.

### CODE REVIEW

**Comment by jtr13** [comment]
That didn't go too well.

```
> pr_fetch(5)
✔ Setting active project to '/Users/JoyceRobbins/usethis_demos'
✔ Checking out PR 'jtr13/usethis_demos/#5' (@jennybc): 'Do I have superpowers?'
ℹ Note that user does NOT allow maintainer to modify this PR at this time,
  although this can be changed.
✔ Adding remote 'jennybc' as 'https://github.com/jennybc/usethis_demos.git'
✔ Creating local branch 'jennybc-jenny-superpowers-test'
✔ Setting upstream tracking branch for 'jennybc-jenny-superpowers-test' to 'jennybc/jenny-superpowers-test'
✔ Switching to branch 'jennybc-jenny-superpowers-test'
> pr_push()
✔ Checking that local branch 'jennybc-jenny-superpowers-test' has the changes in 'jennybc/jenny-superpowers-test'
✔ Pushing local 'jennybc-jenny-superpowers-test' branch to 'jennybc:jenny-superpowers-test'
Error: The push was not successful. Consider that user can decline to allow
maintainers to modify a PR.
> pr <- gh::gh(
+     "PATCH /repos/:owner/:repo/pulls/:number",
+     owner = "jtr13",
+     repo = "usethis-demos",
+     number = 5,
+     maintainer_can_modify = TRUE,
+     .token = Sys.getenv("GITHUB_PAT")
+ )
Error in gh::gh("PATCH /repos/:owner/:repo/pulls/:number", owner = "jtr13",  : 
  GitHub API error (404): 404 Not Found
  Not Found
```

**Comment by jtr13** [comment]
Btw, other stuff using the token like `usethis::use_github()` works fine.

**Comment by jennybc** [comment]
What if you fix my typo in the repo name? 😉

So "usethis_demos" instead of "usethis-demos".

**Comment by jtr13** [comment]
That did it. I will use my new powers responsibly. 💪

**Comment by jennybc** [comment]
Yeah this appears to be a general phenomenon. I've asked GitHub if this is how the feature is supposed to work. If so, I don't really see the point of giving the user the feeling of control.

**Comment by jtr13** [comment]
Exactly. If it's by design then it's not good design.

**Pull request closed without merging**
